FROM ubuntu:latest

# Set environment variables
ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8
ENV JAVA_VERSION=jdk-11.0.11+9
ENV JAVA_HOME=/opt/java/openjdk
ENV PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV MAVEN_HOME=/usr/share/maven
ENV MAVEN_CONFIG=/root/.m2

# Update and install dependencies
RUN apt-get update && apt-get install -y \
    curl \
    wget \
    gnupg \
    apt-transport-https

# Set up OpenJDK
RUN set -eux; \
    apt-get install -y openjdk-11-jdk

# Set up Maven
ARG MAVEN_VERSION=3.8.1
ARG USER_HOME_DIR=/root
ARG SHA=0ec48eb515d93f8515d4abe465570dfded6fa13a3ceb9aab8031428442d9912ec20f066b2afbf56964ffe1ceb56f80321b50db73cf77a0e2445ad0211fb8e38d
ARG BASE_URL=https://apache.osuosl.org/maven/maven-3/3.8.1/binaries

RUN mkdir -p /usr/share/maven /usr/share/maven/ref \
  && wget -O /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
  && echo "${SHA}  /tmp/apache-maven.tar.gz" | sha256sum -c - \
  && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 \
  && rm -f /tmp/apache-maven.tar.gz

COPY mvn-entrypoint.sh /usr/local/bin/mvn-entrypoint.sh
COPY /usr/share/maven/ref/ /usr/share/maven/ref/

ENTRYPOINT ["/usr/local/bin/mvn-entrypoint.sh"]
CMD ["mvn"]

# Additional commands
RUN apt update
RUN apt install -y docker.io
