apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-react-app
  labels:
    app: vite-react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vite-react-app
  template:
    metadata:
      labels:
        app: vite-react-app
    spec:
      containers:
      - name: vite-react-app
        image: anideepkalia/react-app:replaceImageTag   # replace replaceImageTag with actual one
        ports:
        - containerPort: 8080
